<?php

namespace ContainerNTnhWJ4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A2UKxPjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.a2UKxPj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.a2UKxPj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'client' => ['privates', '.errored..service_locator.a2UKxPj.App\\Entity\\Client', NULL, 'Cannot autowire service ".service_locator.a2UKxPj": it references class "App\\Entity\\Client" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'client' => 'App\\Entity\\Client',
            'entityManager' => '?',
        ]);
    }
}
