<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNTnhWJ4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNTnhWJ4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNTnhWJ4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNTnhWJ4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNTnhWJ4\App_KernelDevDebugContainer([
    'container.build_hash' => 'NTnhWJ4',
    'container.build_id' => 'b1686996',
    'container.build_time' => 1638911219,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNTnhWJ4');
